# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 09:39
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='名称')),
                ('shortcut', models.CharField(max_length=120, unique=True, verbose_name='字母缩写')),
            ],
            options={
                'verbose_name_plural': '栏目分类',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240, verbose_name='文章标题')),
                ('source', models.CharField(blank=True, db_index=True, max_length=240, null=True, verbose_name='来源')),
                ('isMedia', models.BooleanField(db_index=True, default=False, verbose_name='媒体吗')),
                ('content', ckeditor.fields.RichTextField(max_length=1024, verbose_name='文章内容')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('published_date', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField(default=False)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Category', verbose_name='文章类型')),
            ],
            options={
                'verbose_name_plural': '文章',
            },
        ),
        migrations.CreateModel(
            name='EncodeFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='UTF-8', max_length=120, unique=True, verbose_name='编码格式')),
            ],
            options={
                'verbose_name_plural': '编码格式',
            },
        ),
        migrations.AddField(
            model_name='content',
            name='encodeformat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.EncodeFormat', verbose_name='编码格式'),
        ),
    ]
